FROM golang:{{ .GoVersion }} as builder

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY cmd cmd
COPY internal internal

ENV CGO_ENABLED=0
RUN go build -o {{ .AppName }} ./cmd/{{ .AppName }}/main.go

FROM alpine:latest

RUN apk update

COPY configs configs

COPY --from=builder /app/{{ .AppName }} {{ .AppName }}

CMD ["./{{ .AppName }}"]
